version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8000:80
    restart: always

  node:
    build:
      context: ./node
    container_name: node
    volumes:
      - ./node:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - nginx
    ports:
      - 3000:3000